# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Thread-Suspend
version:      1.06
version_from: lib/Thread/Suspend.pm
installdirs:  site
requires:
    Test::More:                    0.5
    threads:                       1.36
    threads::shared:               1.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
