--- #YAML:1.0
name:                Thread-Suspend
version:             1.12
abstract:            Suspend and resume operations for threads
license:             perl
author:              
    - Jerry D. Hedden <jdhedden AT cpan DOT org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0.5
    threads:                       1.39
    threads::shared:               1.01
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
