--- #YAML:1.0
name:               Thread-Suspend
version:            1.21
abstract:           Suspend and resume operations for threads
author:
    - Jerry D. Hedden <jdhedden AT cpan DOT org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:       0.5
    threads:          1.39
    threads::shared:  1.01
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.5601
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
